stages:
  - build
  - latest

variables:
  PHP_7_2: 7.2.33
  PHP_7_3: 7.3.21
  PHP_7_4: 7.4.9
  PHP_8_0: 8.0-rc

.build:
  stage: build
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - wget https://github.com/hairyhenderson/gomplate/releases/download/v3.7.0/gomplate_linux-amd64-slim -O /usr/local/bin/gomplate
    - chmod +x /usr/local/bin/gomplate
    - gomplate -f build.sh.tmpl -o build.sh
    - sh build.sh
  after_script:
    - cat build.sh

# PHP 7.2
# =========================================

build-next-7-2:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: next-7.2
    PHP_BASEIMAGE_VERSION: $PHP_7_2
    CACHE_FROM: $CI_REGISTRY_IMAGE:next-7.2
  only:
    - next

build-master-7-2:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: latest-7.2
    PHP_BASEIMAGE_VERSION: $PHP_7_2
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.2
  only:
    - master

build-tags-7-2:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME-7.2
    PHP_BASEIMAGE_VERSION: $PHP_7_2
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.2
  only:
    - tags

# PHP 7.3
# =========================================

build-next-7-3:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: next-7.3
    PHP_BASEIMAGE_VERSION: $PHP_7_3
    CACHE_FROM: $CI_REGISTRY_IMAGE:next-7.3
  only:
    - next

build-master-7-3:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: latest-7.3
    PHP_BASEIMAGE_VERSION: $PHP_7_3
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.3
  only:
    - master

build-tags-7-3:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME-7.3
    PHP_BASEIMAGE_VERSION: $PHP_7_3
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.3
  only:
    - tags

# PHP 7.4
# =========================================

build-next-7-4:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: next-7.4
    PHP_BASEIMAGE_VERSION: $PHP_7_4
    CACHE_FROM: $CI_REGISTRY_IMAGE:next-7.4
  only:
    - next

build-master-7-4:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: latest-7.4
    PHP_BASEIMAGE_VERSION: $PHP_7_4
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.4
  only:
    - master

build-tags-7-4:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME-7.4
    PHP_BASEIMAGE_VERSION: $PHP_7_4
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.4
  only:
    - tags

# PHP 8.0
# =========================================

build-next-8-0:
  extends: .build
  variables:
    DOCKER_IMAGE_TAG: next-8.0-rc
    PHP_BASEIMAGE_VERSION: $PHP_8_0
    XDEBUG_VERSION: master
    PHP_EXTENSIONS: "dom exif gd iconv intl mysqli opcache pdo_mysql pdo_sqlite soap xsl zip"
    CACHE_FROM: $CI_REGISTRY_IMAGE:next-8.0-rc
  only:
    - next

# Latest
# =========================================

build-next-latest:
  extends: .build
  stage: latest
  variables:
    DOCKER_IMAGE_TAG: next
    PHP_BASEIMAGE_VERSION: $PHP_7_4
    CACHE_FROM: $CI_REGISTRY_IMAGE:next-7.4
  only:
    - next

build-master-latest:
  extends: .build
  stage: latest
  variables:
    DOCKER_IMAGE_TAG: latest
    PHP_BASEIMAGE_VERSION: $PHP_7_4
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.4
  only:
    - master

build-tags-latest:
  extends: .build
  stage: latest
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME
    PHP_BASEIMAGE_VERSION: $PHP_7_4
    CACHE_FROM: $CI_REGISTRY_IMAGE:latest-7.4
  only:
    - tags
